// utils/api.ts
import { Message } from '../types/message';
import { MOSAComponentGraph } from '../types/MOSA';

export async function sendMessageToAI(message: Message): Promise<{
  response: Message;
  summary: string;
  mosa: MOSAComponentGraph;
}> {
  // Mock AI response
  return new Promise(resolve =>
    setTimeout(() => {
      resolve({
        response: {
          id: crypto.randomUUID(),
          role: 'ai',
          text: `AI reply to "${message.text}"`,
        },
        summary: `Summary after message "${message.text}"`,
        mosa: {
          system_name: 'Sample System',
          description: 'Auto-generated by AI',
          components: [],
          connections: [],
        },
      });
    }, 1000)
  );
}

export async function saveMessageToDB(payload: {
  id: string;
  sentMessage: Message;
  receivedMessage: Message;
  updatedSummary: string;
  updatedMOSA: MOSAComponentGraph;
}) {
  // Simulate save
  console.log('Saving to DB:', payload);
  return Promise.resolve();
}
